name: Publicar en GitHub Pages

on:
  push:
    branches:
      - master  # o el nombre de tu rama principal

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del c칩digo
      uses: actions/checkout@v2

    - name: Configurar Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.2'

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install Flask
        pip install sympy

    # Ejecuta tu archivo main.py
    - name: Ejecutar main.py
      run: python main.py &

    # Copia los archivos est치ticos necesarios al directorio de despliegue
    - name: Copiar archivos est치ticos
      run: cp -r templates/* $GITHUB_WORKSPACE

    # Utiliza la acci칩n para desplegar en GitHub Pages
    - name: Desplegar en GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: $GITHUB_WORKSPACE
